"""Add 2FA and Passkeys

Revision ID: 09350dfd8ecc
Revises: fc209dc56a6f
Create Date: 2026-03-03 09:27:59.038415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '09350dfd8ecc'
down_revision = 'fc209dc56a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_passkeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    with op.batch_alter_table('user_passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_passkeys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_secret')

    with op.batch_alter_table('user_passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_passkeys_user_id'))

    op.drop_table('user_passkeys')
    # ### end Alembic commands ###
