"""add is_favorite to collections

Revision ID: 0e84ff890db1
Revises: e2b98ad1347d
Create Date: 2026-02-21 21:47:03.251138

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e84ff890db1"
down_revision = "e2b98ad1347d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_favorite", sa.Boolean(), server_default=sa.text("0"), nullable=False
            )
        )

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.alter_column("is_favorite", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("is_favorite")

    # ### end Alembic commands ###
