"""perf: add index to snipsels.deleted_at

Revision ID: 1826e10f56de
Revises: d77b97bca4e8
Create Date: 2026-04-12 18:13:20.817459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1826e10f56de'
down_revision = 'd77b97bca4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsels_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsels_deleted_at'))

    # ### end Alembic commands ###
