"""add ai prompt history

Revision ID: 1fc39a90bbc0
Revises: b3c4d5e6f7a8
Create Date: 2026-04-14 22:17:50.194145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc39a90bbc0'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompt_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prompt', name='uq_ai_prompt_history_user_prompt')
    )
    with op.batch_alter_table('ai_prompt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_prompt_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('collection_snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_snipsels_snipsel_collection'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_snipsels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_snipsels_snipsel_collection'), ['snipsel_id', 'collection_id'], unique=False)

    with op.batch_alter_table('ai_prompt_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_prompt_history_user_id'))

    op.drop_table('ai_prompt_history')
    # ### end Alembic commands ###
