"""add notifications table

Revision ID: 28b45004eb13
Revises: 9f2a5b1a2c77
Create Date: 2026-02-25 08:00:32.564918

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '28b45004eb13'
down_revision = '9f2a5b1a2c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('snipsel_id', sa.String(length=36), nullable=True),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('collection_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_favorites_collection_id'))
        batch_op.drop_index(batch_op.f('ix_collection_favorites_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_favorites_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_favorites_collection_id'), ['collection_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
