"""add ai configuration fields to user

Revision ID: 2ce60fc4c9df
Revises: e4a7c0e1e02c
Create Date: 2026-03-14 17:37:35.331103

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ce60fc4c9df"
down_revision = "e4a7c0e1e02c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_llm_url", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("ai_model_name", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("ai_api_key", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("ai_api_key")
        batch_op.drop_column("ai_model_name")
        batch_op.drop_column("ai_llm_url")

    # ### end Alembic commands ###
