"""add reactions table

Revision ID: 36af93c9e826
Revises: ae59e7ba3829
Create Date: 2026-03-02 13:45:59.717124

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '36af93c9e826'
down_revision = 'ae59e7ba3829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snipsel_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snipsel_id', 'user_id', 'emoji', name='uq_snipsel_reaction_user_emoji')
    )
    with op.batch_alter_table('snipsel_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsel_reactions_snipsel_id'), ['snipsel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snipsel_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsel_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsel_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_snipsel_reactions_snipsel_id'))

    op.drop_table('snipsel_reactions')
    # ### end Alembic commands ###
