"""add geo fields to snipsels

Revision ID: 47d7b2bbc7a5
Revises: 0e84ff890db1
Create Date: 2026-02-21 23:53:11.003284

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47d7b2bbc7a5"
down_revision = "0e84ff890db1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("geo_lat", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("geo_lng", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("geo_accuracy_m", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.drop_column("geo_accuracy_m")
        batch_op.drop_column("geo_lng")
        batch_op.drop_column("geo_lat")

    # ### end Alembic commands ###
