"""add user theme preference

Revision ID: 4988a6a8e1fa
Revises: c47323cb92d7
Create Date: 2026-02-27 23:04:32.120502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4988a6a8e1fa'
down_revision = 'c47323cb92d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=False, server_default='system'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
