"""Add header image zoom and horizontal position

Revision ID: 577fe0825309
Revises: e52dd340bedb
Create Date: 2026-03-04 11:38:13.292735

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "577fe0825309"
down_revision = "e52dd340bedb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("header_image_x_position", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("header_image_zoom", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("header_image_zoom")
        batch_op.drop_column("header_image_x_position")

    # ### end Alembic commands ###
