"""initial

Revision ID: 642af4f4fe7b
Revises: 
Create Date: 2026-02-20 17:33:38.112301

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '642af4f4fe7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('header_image_url', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('list_for_day', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'list_for_day', name='uq_collection_owner_day')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('ix_collections_owner_archived', ['owner_user_id', 'archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_mentions_owner_name')
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentions_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('snipsels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('text', 'task', 'link_external', 'link_internal', 'attachment', 'image', name='snipsel_type'), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('task_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('done_by_id', sa.String(length=36), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('external_label', sa.Text(), nullable=True),
    sa.Column('internal_target_snipsel_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('(task_done = 0) OR (task_done = 1)', name='ck_snipsels_task_done_bool'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['done_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['internal_target_snipsel_id'], ['snipsels.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsels_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snipsels_type'), ['type'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_tags_owner_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_snipsel_id'), ['snipsel_id'], unique=False)

    op.create_table('collection_snipsels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('indent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('indent >= 0', name='ck_collection_snipsels_indent_nonneg'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'snipsel_id', name='uq_collection_snipsel')
    )
    with op.batch_alter_table('collection_snipsels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_snipsels_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index('ix_collection_snipsels_collection_position', ['collection_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_snipsels_snipsel_id'), ['snipsel_id'], unique=False)

    op.create_table('snipsel_links',
    sa.Column('from_snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('to_snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_snipsel_id'], ['snipsels.id'], ),
    sa.ForeignKeyConstraint(['to_snipsel_id'], ['snipsels.id'], ),
    sa.PrimaryKeyConstraint('from_snipsel_id', 'to_snipsel_id')
    )
    with op.batch_alter_table('snipsel_links', schema=None) as batch_op:
        batch_op.create_index('ix_snipsel_links_to', ['to_snipsel_id'], unique=False)

    op.create_table('snipsel_mentions',
    sa.Column('snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('mention_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.PrimaryKeyConstraint('snipsel_id', 'mention_id')
    )
    op.create_table('snipsel_tags',
    sa.Column('snipsel_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['snipsel_id'], ['snipsels.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('snipsel_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snipsel_tags')
    op.drop_table('snipsel_mentions')
    with op.batch_alter_table('snipsel_links', schema=None) as batch_op:
        batch_op.drop_index('ix_snipsel_links_to')

    op.drop_table('snipsel_links')
    with op.batch_alter_table('collection_snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_snipsels_snipsel_id'))
        batch_op.drop_index('ix_collection_snipsels_collection_position')
        batch_op.drop_index(batch_op.f('ix_collection_snipsels_collection_id'))

    op.drop_table('collection_snipsels')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_snipsel_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_owner_user_id'))

    op.drop_table('tags')
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsels_type'))
        batch_op.drop_index(batch_op.f('ix_snipsels_owner_user_id'))

    op.drop_table('snipsels')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentions_owner_user_id'))

    op.drop_table('mentions')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_owner_user_id'))
        batch_op.drop_index('ix_collections_owner_archived')

    op.drop_table('collections')
    op.drop_table('users')
    # ### end Alembic commands ###
