"""Add show_completed_tasks to collections

Revision ID: 6f0594f49a04
Revises: cfb5eaa9ce7c
Create Date: 2026-03-08 18:15:32.236794

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f0594f49a04"
down_revision = "cfb5eaa9ce7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "show_completed_tasks",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("show_completed_tasks")

    # ### end Alembic commands ###
