"""add habits tables

Revision ID: 781ded07f37f
Revises: ec7f179792f8
Create Date: 2026-05-20 10:54:47.443130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781ded07f37f'
down_revision = 'ec7f179792f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('reminder_rrule', sa.Text(), nullable=True),
    sa.Column('sort_position', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index('ix_habits_owner_archived', ['owner_user_id', 'is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_habits_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('habit_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('habit_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'user_id', 'completed_date', name='uq_habit_completion_habit_user_date')
    )
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.create_index('ix_habit_completions_habit_date', ['habit_id', 'completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_completions_habit_id'), ['habit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_completions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_habit_completions_habit_id'))
        batch_op.drop_index('ix_habit_completions_habit_date')

    op.drop_table('habit_completions')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_owner_user_id'))
        batch_op.drop_index('ix_habits_owner_archived')

    op.drop_table('habits')
    # ### end Alembic commands ###
