"""Add exclude_from_todo_list to Collection

Revision ID: 7965a04720a1
Revises: e378ff50303a
Create Date: 2026-04-21 22:59:21.722810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7965a04720a1'
down_revision = 'e378ff50303a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_from_todo_list', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_todo_list')

    # ### end Alembic commands ###
