"""add carry_over_open_tasks to users

Revision ID: 8735f6f3794b
Revises: e8bd76aff901
Create Date: 2026-02-22 13:46:09.034599

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8735f6f3794b"
down_revision = "e8bd76aff901"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "carry_over_open_tasks",
                sa.Boolean(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("carry_over_open_tasks", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("carry_over_open_tasks")

    # ### end Alembic commands ###
