"""add card_view to snipsels

Revision ID: a1b2c3d5e7f9
Revises: 2ce60fc4c9df
Create Date: 2026-03-19 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1b2c3d5e7f9"
down_revision = "2ce60fc4c9df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("card_view", sa.Boolean(), nullable=True, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.drop_column("card_view")

    # ### end Alembic commands ###
