"""add snipsel reminders

Revision ID: ae59e7ba3829
Revises: 4988a6a8e1fa
Create Date: 2026-02-28 18:44:26.534296

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae59e7ba3829"
down_revision = "4988a6a8e1fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reminder_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("reminder_rrule", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snipsels", schema=None) as batch_op:
        batch_op.drop_column("reminder_rrule")
        batch_op.drop_column("reminder_at")

    # ### end Alembic commands ###
