"""add background color fields to user

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d5e7f9
Create Date: 2026-03-20 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2c3d4e5f6g7"
down_revision = "a1b2c3d5e7f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("light_background_color", sa.String(length=7), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dark_background_color", sa.String(length=7), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("dark_background_color")
        batch_op.drop_column("light_background_color")

    # ### end Alembic commands ###
