"""add diced_moments_tags to user

Revision ID: b2efec622b00
Revises: 7965a04720a1
Create Date: 2026-04-26 15:45:57.829290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2efec622b00'
down_revision = '7965a04720a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diced_moments_tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('diced_moments_tags')

    # ### end Alembic commands ###
