"""add twos_id to collections

Revision ID: c47323cb92d7
Revises: a1b2c3d4e5f6
Create Date: 2026-02-27 20:15:01.497228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c47323cb92d7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twos_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_collections_twos_id'), ['twos_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_twos_id'))
        batch_op.drop_column('twos_id')

    # ### end Alembic commands ###
