"""Add public_token to Collection

Revision ID: cfb5eaa9ce7c
Revises: 577fe0825309
Create Date: 2026-03-05 09:20:06.407585

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cfb5eaa9ce7c'
down_revision = '577fe0825309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_collections_public_token'), ['public_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_public_token'))
        batch_op.drop_column('public_token')

    # ### end Alembic commands ###
