"""perf: add geo and relationship indices

Revision ID: d77b97bca4e8
Revises: a1b2c3d4e5f7
Create Date: 2026-04-12 17:56:31.346352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77b97bca4e8'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsel_collection_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsel_collection_refs_collection_id'), ['collection_id'], unique=False)

    with op.batch_alter_table('snipsel_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsel_mentions_mention_id'), ['mention_id'], unique=False)

    with op.batch_alter_table('snipsel_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsel_tags_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snipsels_geo_lat'), ['geo_lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_snipsels_geo_lng'), ['geo_lng'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsels_geo_lng'))
        batch_op.drop_index(batch_op.f('ix_snipsels_geo_lat'))

    with op.batch_alter_table('snipsel_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsel_tags_tag_id'))

    with op.batch_alter_table('snipsel_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsel_mentions_mention_id'))

    with op.batch_alter_table('snipsel_collection_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsel_collection_refs_collection_id'))

    # ### end Alembic commands ###
