"""add header_color to collections and default_collection_header_color to users

Revision ID: e2b98ad1347d
Revises: 642af4f4fe7b
Create Date: 2026-02-21 20:23:06.613095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e2b98ad1347d'
down_revision = '642af4f4fe7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_collection_header_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_collection_header_color')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('header_color')

    # ### end Alembic commands ###
