"""Change task_done column type from Boolean to Integer

Revision ID: e378ff50303a
Revises: 74c955bc45a4
Create Date: 2026-04-21 09:09:51.479034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e378ff50303a'
down_revision = '74c955bc45a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.alter_column('task_done',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.alter_column('task_done',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
