"""add mute_notifications to collections

Revision ID: e4a7c0e1e02c
Revises: 6f0594f49a04
Create Date: 2026-03-14 16:06:33.546926

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e4a7c0e1e02c'
down_revision = '6f0594f49a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mute_notifications', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('mute_notifications')

    # ### end Alembic commands ###
