"""Add collection header image support

Revision ID: e52dd340bedb
Revises: 09350dfd8ecc
Create Date: 2026-03-04 10:44:47.748249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e52dd340bedb'
down_revision = '09350dfd8ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('snipsel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_attachments_collection_id'), ['collection_id'], unique=False)
        batch_op.create_foreign_key('fk_attachments_collection_id', 'collections', ['collection_id'], ['id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_image_position', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('header_image_position')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attachments_collection_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attachments_collection_id'))
        batch_op.alter_column('snipsel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('collection_id')

    # ### end Alembic commands ###
