"""add snipsel_collection_refs table

Revision ID: e86e8aa21a68
Revises: 28b45004eb13
Create Date: 2026-02-26 09:26:34.660183

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e86e8aa21a68"
down_revision = "28b45004eb13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snipsel_collection_refs",
        sa.Column("snipsel_id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snipsel_id"],
            ["snipsels.id"],
        ),
        sa.PrimaryKeyConstraint("snipsel_id", "collection_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snipsel_collection_refs")
    # ### end Alembic commands ###
