"""add default_snipsel_type to collections

Revision ID: e8bd76aff901
Revises: 47d7b2bbc7a5
Create Date: 2026-02-22 13:14:20.402623

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e8bd76aff901'
down_revision = '47d7b2bbc7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_snipsel_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('default_snipsel_type')

    # ### end Alembic commands ###
