"""add diced_count to snipsel

Revision ID: ec7f179792f8
Revises: b2efec622b00
Create Date: 2026-04-26 15:53:36.947025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7f179792f8'
down_revision = 'b2efec622b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diced_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_snipsels_diced_count'), ['diced_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snipsels_diced_count'))
        batch_op.drop_column('diced_count')

    # ### end Alembic commands ###
