"""Add user_api_keys table for API key authentication

Revision ID: ed22a41367db
Revises: b2c3d4e5f6g7
Create Date: 2026-03-23 21:40:35.165366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed22a41367db'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.alter_column('card_view',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snipsels', schema=None) as batch_op:
        batch_op.alter_column('card_view',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))

    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
